-- Migration: Replace MAX(rol)+1 trigger with GENERATED BY DEFAULT AS IDENTITY
-- Behavior identical to old system (tbmembro.id): auto-increment OR accept any manual value.

-- Step 1: Drop the trigger and function
DROP TRIGGER IF EXISTS trg_members_set_rol ON members;
DROP FUNCTION IF EXISTS members_set_rol_on_insert();

-- Step 2: Drop any leftover default/sequence
ALTER TABLE "members" ALTER COLUMN "rol" DROP DEFAULT;

-- Step 3: Add IDENTITY to the column (GENERATED BY DEFAULT = accepts manual override)
ALTER TABLE "members"
  ALTER COLUMN "rol" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Step 4: Sync the sequence to the current highest ROL so next auto-value continues from there
SELECT setval(
  pg_get_serial_sequence('"members"', 'rol'),
  COALESCE((SELECT MAX(rol) FROM members WHERE rol IS NOT NULL), 0) + 1,
  false  -- false = next INSERT gets exactly this value
);
