CREATE TABLE IF NOT EXISTS "tbcampo" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "estado" VARCHAR(255),
    "campo" VARCHAR(255),
    "presidente" VARCHAR(255),
    "sede" VARCHAR(255),
    "senha" VARCHAR(255) DEFAULT '',
    CONSTRAINT "tbcampo_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "tbcampo" DROP COLUMN IF EXISTS "rash";

CREATE TABLE IF NOT EXISTS "regional" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "regional" VARCHAR(255),
    "idsede" VARCHAR(255),
    "campo" VARCHAR(255),
    CONSTRAINT "tbregional_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "regional" DROP COLUMN IF EXISTS "rash";

CREATE TABLE IF NOT EXISTS "tbigrejasede" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "instagram" VARCHAR(255),
    "site" VARCHAR(255),
    "youtube" VARCHAR(255),
    "tictoc" VARCHAR(255),
    "facebook" VARCHAR(255),
    "contato" VARCHAR(255),
    "rua" VARCHAR(255),
    "numero" VARCHAR(255),
    "cidade" VARCHAR(255),
    "estado" VARCHAR(255),
    "pais" VARCHAR(255),
    "bairro" VARCHAR(255),
    "mostrar" BOOLEAN,
    "cnpj" VARCHAR(255),
    "pagamentoTokenUm" VARCHAR(255),
    "pagamentoTokenDois" VARCHAR(255),
    "regional" VARCHAR(255),
    "campo" VARCHAR(255),
    "igreja" VARCHAR(255),
    "idigrejasede" BIGINT,
    "agendapdf" VARCHAR(255),
    "pix" VARCHAR(255),
    "banco" VARCHAR(255),
    CONSTRAINT "tbigrejasede_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "tbigrejasede" DROP COLUMN IF EXISTS "rash";

CREATE TABLE IF NOT EXISTS "tbigreja" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "igreja" VARCHAR(255) DEFAULT '0',
    "idtbregional" VARCHAR(255) DEFAULT '0',
    "idtbsede" VARCHAR(255) DEFAULT '0',
    "hierarquia" VARCHAR(255) DEFAULT '0',
    "tipodocumento" VARCHAR(255) DEFAULT '0',
    "documento" VARCHAR(255) DEFAULT '0',
    "datafundacao" VARCHAR(255) DEFAULT '0',
    "cep" VARCHAR(255) DEFAULT '0',
    "pais" VARCHAR(255) DEFAULT '0',
    "estado" VARCHAR(255) DEFAULT '0',
    "cidade" VARCHAR(255) DEFAULT '0',
    "bairro" VARCHAR(255) DEFAULT '0',
    "logradouro" VARCHAR(255) DEFAULT '0',
    "regional" VARCHAR(255) DEFAULT '0',
    "temploproprio" BOOLEAN DEFAULT true,
    "campo" VARCHAR(255) DEFAULT '0',
    "idfirebase" VARCHAR(255) DEFAULT '0',
    "obs" VARCHAR(255) DEFAULT '0',
    "igrejapai" VARCHAR(255) DEFAULT '0',
    "ativo" BOOLEAN DEFAULT true,
    "codigo" BIGINT DEFAULT 0,
    "nomeplaca" VARCHAR(255) DEFAULT '0',
    "dirigente" VARCHAR(255) DEFAULT '0',
    "entrada" VARCHAR(255) DEFAULT '0',
    "saida" VARCHAR(255) DEFAULT '0',
    "roldirigente" BIGINT DEFAULT 0,
    CONSTRAINT "tbigreja_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tbigreja_id_key" UNIQUE ("id")
);

CREATE TABLE IF NOT EXISTS "tbigrejafoto" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "idtbigreja" BIGINT,
    "foto" VARCHAR(255),
    "campo" VARCHAR(255),
    CONSTRAINT "tbigrejafoto_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "tbigrejafoto" DROP COLUMN IF EXISTS "rash";