ALTER TABLE "members"
ADD COLUMN IF NOT EXISTS "spouse_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "naturality_city" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "naturality_state" VARCHAR(2),
ADD COLUMN IF NOT EXISTS "nationality" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "voter_registration" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "voter_zone" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "voter_section" VARCHAR(10);